
[workspace.package]
name = "efir"
version = "0.1.0"
edition = "2024"
description = "A minimal internet radio for the terminal"

repository = "https://github.com/naylour/efir"
homepage = "https://github.com/naylour/efir"
readme = "README.md"

keywords = ["radio", "tui", "terminal", "audio", "music"]
categories = ["command-line-utilities", "multimedia::audio"]

[workspace]
resolver = "3"
members = [
    "apps/efir-term",
    "crates/efir-audio",
    "crates/efir-catalog",
    "crates/efir-core",
    "crates/efir-tui",
]


[workspace.dependencies]


[profile.dev]
opt-level = 0
debug = true
strip = "none"
debug-assertions = true
overflow-checks = true
incremental = true
panic = "unwind"

[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
incremental = true

[profile.release]
opt-level = "s"
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = "fat"
codegen-units = 1
incremental = false
panic = "abort"

[profile.dist]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
