
[package]
name = "efir"
version = "0.1.0"
edition = "2024"
description = "A minimal internet radio for the terminal"

repository = "https://github.com/naylour/efir"
homepage = "https://github.com/naylour/efir"
readme = "README.md"

keywords = ["radio", "tui", "terminal", "audio", "music"]
categories = ["command-line-utilities", "multimedia::audio"]

[dependencies]
